name: test-snap-fran
version: 0.0.2
summary: Just a test python snap
description: >
  Just a test python snap

confinement: strict
base: core18

parts:
  test-snap-fran:
    plugin: python
    python-version: python3
    source: .

apps:
  test-snap-fran:
    command: python3 test_snap.py
